[package]
name = "offer-guard"
version = "0.1.0"
edition = "2024"

[dependencies]
ckb-std = "1.1"
k256 = { version = "0.13", default-features = false, features = ["ecdsa", "alloc"] }
sha3 = { version = "0.10", default-features = false }

[features]
library = []
native-simulator = ["library", "ckb-std/native-simulator"]
