import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :web, WebWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LKB0MbPV/UvJXzdzPnNOKqiJwYVX/kxH1cLgCj5vZudvaYM4LiWPcNdZdyZXl4d5",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:web, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# The local devnet this app reads from and builds transactions against
# (see ../devnet-ops and ../devnet) -- every hash/outpoint below is
# specific to THIS devnet's current deployment and changes if the devnet
# is ever reset and redeployed (rerun the relevant devnet-ops binary and
# copy its JSON output's values back in here). `data1` is the CKB VM
# version every contract binary here was compiled for (they use the
# Zba/Zbb/Zbc/Zbs bit-manipulation extensions, only available from VM
# version 1 onward); each `code_hash` is blake2b_256 of the raw binary
# bytes, matching devnet-ops's own `deployed_binary_cell_dep` convention.
config :web, :ckb,
  rpc_url: "http://127.0.0.1:8114",
  sighash_code_hash: "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
  # See devnet-ops's own sighash_cell_dep() doc comment: this MUST be a
  # dep_group, not a direct code reference, or every signature fails.
  sighash_dep_group: %{tx_hash: "0xc05f08a40fc9879abb49b5a2c32a1e8bc6fa6ce33ed22d0f96bc405b2e267b70", index: 0},
  mpesa_escrow: %{
    code_hash: "0x74e8b52b2043efe2386a5f838a0a0ce44d0d087025e95a575eb40ba38b54e0f9",
    hash_type: "data1",
    cell_dep: %{tx_hash: "0x7d39c6d620218d7725159dcf203ef313d261cd1d10dd195df5c406ee273311be", index: 1}
  },
  claims_registry: %{
    code_hash: "0x5cfd31a4a0775052dd45b85637cabd9086b5f7f5d257227153b583d72f3c1000",
    hash_type: "data1",
    cell_dep: %{tx_hash: "0x7d39c6d620218d7725159dcf203ef313d261cd1d10dd195df5c406ee273311be", index: 0},
    # The one, canonical, permissionless registry cell -- see
    # devnet-ops/src/remint_registry.rs. cell: where the LIVE cell
    # currently is (changes every claim, since it's consume-and-recreate;
    # the API looks this up live, this is just the identity/type info).
    type_hash: "0x3e8ab4b40421d56337f3204b0fb0fa2e96f9bf9bc322e3142e5e4d5778b694c5",
    type_args: "0x9d95b002b5c5c6c0910522c302bef36d0a3183208f28521c4a0f8a3bf581839c",
    genesis_out_point: %{tx_hash: "0x8a3e189a89df7ac36fc4aa310573961a544e3d38177b2f4c458b7b519f158c81", index: 0}
  },
  offer_guard: %{
    code_hash: "0x13c3c2b25bda33139e4d0ba52868b478d98d47c166d979e18898a3b8cfa786ba",
    hash_type: "data1",
    cell_dep: %{tx_hash: "0x7d39c6d620218d7725159dcf203ef313d261cd1d10dd195df5c406ee273311be", index: 2}
  },
  always_success: %{
    code_hash: "0xfd5c9693329386bf61812189788840c4438240b2ec536385a51e473c48727d1a",
    hash_type: "data1",
    cell_dep: %{tx_hash: "0x9069c933d8d72320412fea8bc5adbb57d981f8a47740077faff2a6070fbccb39", index: 0}
  },
  # The trusted Verifier's own key. This MVP colocates it with Phoenix as
  # a stand-in for Ken's real, separate off-chain TLSNotary Verifier
  # service (see Web.Ckb.Verifier's own moduledoc) -- reusing the exact
  # key devnet-ops/verifier_key.txt already generated, so offers created
  # through the UI and offers created through devnet-ops's own scripts
  # trust the same identity. Override via BITSHADA_VERIFIER_PRIVATE_KEY
  # for anything other than this exact devnet.
  verifier_private_key:
    System.get_env(
      "BITSHADA_VERIFIER_PRIVATE_KEY",
      "0xf772d0917cd21824b6259816aa2da2a9675e7ff25b8a5e41703c34cb6d05a30e"
    )
